/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransportMasterRouteImport } from './routes/transport-master'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as DeliveryChallansIndexRouteImport } from './routes/delivery-challans.index'
import { Route as DeliveryChallansNewRouteImport } from './routes/delivery-challans.new'
import { Route as InsightsLogisticsSummaryRouteImport } from './routes/insights.logistics-summary'
import { Route as MaterialMovementPendingRegisterRouteImport } from './routes/material-movement.pending-register'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ReportsStockWithPartyRouteImport } from './routes/reports.stock-with-party'
import { Route as StockGroupsIndexRouteImport } from './routes/stock-groups.index'
import { Route as StockGroupsNewRouteImport } from './routes/stock-groups.new'
import { Route as StockRegisterIndexRouteImport } from './routes/stock-register.index'
import { Route as TransportMasterIndexRouteImport } from './routes/transport-master.index'
import { Route as TransportMasterNewRouteImport } from './routes/transport-master.new'
import { Route as CustomersEditIdRouteImport } from './routes/customers.edit.$id'
import { Route as DeliveryChallansCustomerCustomerNameRouteImport } from './routes/delivery-challans.customer.$customerName'
import { Route as DeliveryChallansEditIdRouteImport } from './routes/delivery-challans.edit.$id'
import { Route as DeliveryChallansPrintIdRouteImport } from './routes/delivery-challans.print.$id'
import { Route as ProductsEditIdRouteImport } from './routes/products.edit.$id'
import { Route as StockGroupsEditIdRouteImport } from './routes/stock-groups.edit.$id'
import { Route as TransportMasterEditIdRouteImport } from './routes/transport-master.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportMasterRoute = TransportMasterRouteImport.update({
  id: '/transport-master',
  path: '/transport-master',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryChallansIndexRoute = DeliveryChallansIndexRouteImport.update({
  id: '/delivery-challans/',
  path: '/delivery-challans/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryChallansNewRoute = DeliveryChallansNewRouteImport.update({
  id: '/delivery-challans/new',
  path: '/delivery-challans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsLogisticsSummaryRoute =
  InsightsLogisticsSummaryRouteImport.update({
    id: '/insights/logistics-summary',
    path: '/insights/logistics-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaterialMovementPendingRegisterRoute =
  MaterialMovementPendingRegisterRouteImport.update({
    id: '/material-movement/pending-register',
    path: '/material-movement/pending-register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStockWithPartyRoute = ReportsStockWithPartyRouteImport.update({
  id: '/reports/stock-with-party',
  path: '/reports/stock-with-party',
  getParentRoute: () => rootRouteImport,
} as any)
const StockGroupsIndexRoute = StockGroupsIndexRouteImport.update({
  id: '/stock-groups/',
  path: '/stock-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockGroupsNewRoute = StockGroupsNewRouteImport.update({
  id: '/stock-groups/new',
  path: '/stock-groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRegisterIndexRoute = StockRegisterIndexRouteImport.update({
  id: '/stock-register/',
  path: '/stock-register/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportMasterIndexRoute = TransportMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransportMasterRoute,
} as any)
const TransportMasterNewRoute = TransportMasterNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransportMasterRoute,
} as any)
const CustomersEditIdRoute = CustomersEditIdRouteImport.update({
  id: '/customers/edit/$id',
  path: '/customers/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryChallansCustomerCustomerNameRoute =
  DeliveryChallansCustomerCustomerNameRouteImport.update({
    id: '/delivery-challans/customer/$customerName',
    path: '/delivery-challans/customer/$customerName',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryChallansEditIdRoute = DeliveryChallansEditIdRouteImport.update({
  id: '/delivery-challans/edit/$id',
  path: '/delivery-challans/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryChallansPrintIdRoute = DeliveryChallansPrintIdRouteImport.update({
  id: '/delivery-challans/print/$id',
  path: '/delivery-challans/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEditIdRoute = ProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StockGroupsEditIdRoute = StockGroupsEditIdRouteImport.update({
  id: '/stock-groups/edit/$id',
  path: '/stock-groups/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportMasterEditIdRoute = TransportMasterEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => TransportMasterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transport-master': typeof TransportMasterRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/delivery-challans/new': typeof DeliveryChallansNewRoute
  '/insights/logistics-summary': typeof InsightsLogisticsSummaryRoute
  '/material-movement/pending-register': typeof MaterialMovementPendingRegisterRoute
  '/products/new': typeof ProductsNewRoute
  '/reports/stock-with-party': typeof ReportsStockWithPartyRoute
  '/stock-groups/new': typeof StockGroupsNewRoute
  '/transport-master/new': typeof TransportMasterNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/delivery-challans/': typeof DeliveryChallansIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/stock-groups/': typeof StockGroupsIndexRoute
  '/stock-register/': typeof StockRegisterIndexRoute
  '/transport-master/': typeof TransportMasterIndexRoute
  '/customers/edit/$id': typeof CustomersEditIdRoute
  '/delivery-challans/customer/$customerName': typeof DeliveryChallansCustomerCustomerNameRoute
  '/delivery-challans/edit/$id': typeof DeliveryChallansEditIdRoute
  '/delivery-challans/print/$id': typeof DeliveryChallansPrintIdRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/stock-groups/edit/$id': typeof StockGroupsEditIdRoute
  '/transport-master/edit/$id': typeof TransportMasterEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/customers/new': typeof CustomersNewRoute
  '/delivery-challans/new': typeof DeliveryChallansNewRoute
  '/insights/logistics-summary': typeof InsightsLogisticsSummaryRoute
  '/material-movement/pending-register': typeof MaterialMovementPendingRegisterRoute
  '/products/new': typeof ProductsNewRoute
  '/reports/stock-with-party': typeof ReportsStockWithPartyRoute
  '/stock-groups/new': typeof StockGroupsNewRoute
  '/transport-master/new': typeof TransportMasterNewRoute
  '/customers': typeof CustomersIndexRoute
  '/delivery-challans': typeof DeliveryChallansIndexRoute
  '/products': typeof ProductsIndexRoute
  '/stock-groups': typeof StockGroupsIndexRoute
  '/stock-register': typeof StockRegisterIndexRoute
  '/transport-master': typeof TransportMasterIndexRoute
  '/customers/edit/$id': typeof CustomersEditIdRoute
  '/delivery-challans/customer/$customerName': typeof DeliveryChallansCustomerCustomerNameRoute
  '/delivery-challans/edit/$id': typeof DeliveryChallansEditIdRoute
  '/delivery-challans/print/$id': typeof DeliveryChallansPrintIdRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/stock-groups/edit/$id': typeof StockGroupsEditIdRoute
  '/transport-master/edit/$id': typeof TransportMasterEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/transport-master': typeof TransportMasterRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/delivery-challans/new': typeof DeliveryChallansNewRoute
  '/insights/logistics-summary': typeof InsightsLogisticsSummaryRoute
  '/material-movement/pending-register': typeof MaterialMovementPendingRegisterRoute
  '/products/new': typeof ProductsNewRoute
  '/reports/stock-with-party': typeof ReportsStockWithPartyRoute
  '/stock-groups/new': typeof StockGroupsNewRoute
  '/transport-master/new': typeof TransportMasterNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/delivery-challans/': typeof DeliveryChallansIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/stock-groups/': typeof StockGroupsIndexRoute
  '/stock-register/': typeof StockRegisterIndexRoute
  '/transport-master/': typeof TransportMasterIndexRoute
  '/customers/edit/$id': typeof CustomersEditIdRoute
  '/delivery-challans/customer/$customerName': typeof DeliveryChallansCustomerCustomerNameRoute
  '/delivery-challans/edit/$id': typeof DeliveryChallansEditIdRoute
  '/delivery-challans/print/$id': typeof DeliveryChallansPrintIdRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/stock-groups/edit/$id': typeof StockGroupsEditIdRoute
  '/transport-master/edit/$id': typeof TransportMasterEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/transport-master'
    | '/customers/new'
    | '/delivery-challans/new'
    | '/insights/logistics-summary'
    | '/material-movement/pending-register'
    | '/products/new'
    | '/reports/stock-with-party'
    | '/stock-groups/new'
    | '/transport-master/new'
    | '/customers/'
    | '/delivery-challans/'
    | '/products/'
    | '/stock-groups/'
    | '/stock-register/'
    | '/transport-master/'
    | '/customers/edit/$id'
    | '/delivery-challans/customer/$customerName'
    | '/delivery-challans/edit/$id'
    | '/delivery-challans/print/$id'
    | '/products/edit/$id'
    | '/stock-groups/edit/$id'
    | '/transport-master/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/customers/new'
    | '/delivery-challans/new'
    | '/insights/logistics-summary'
    | '/material-movement/pending-register'
    | '/products/new'
    | '/reports/stock-with-party'
    | '/stock-groups/new'
    | '/transport-master/new'
    | '/customers'
    | '/delivery-challans'
    | '/products'
    | '/stock-groups'
    | '/stock-register'
    | '/transport-master'
    | '/customers/edit/$id'
    | '/delivery-challans/customer/$customerName'
    | '/delivery-challans/edit/$id'
    | '/delivery-challans/print/$id'
    | '/products/edit/$id'
    | '/stock-groups/edit/$id'
    | '/transport-master/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/transport-master'
    | '/customers/new'
    | '/delivery-challans/new'
    | '/insights/logistics-summary'
    | '/material-movement/pending-register'
    | '/products/new'
    | '/reports/stock-with-party'
    | '/stock-groups/new'
    | '/transport-master/new'
    | '/customers/'
    | '/delivery-challans/'
    | '/products/'
    | '/stock-groups/'
    | '/stock-register/'
    | '/transport-master/'
    | '/customers/edit/$id'
    | '/delivery-challans/customer/$customerName'
    | '/delivery-challans/edit/$id'
    | '/delivery-challans/print/$id'
    | '/products/edit/$id'
    | '/stock-groups/edit/$id'
    | '/transport-master/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TransportMasterRoute: typeof TransportMasterRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
  DeliveryChallansNewRoute: typeof DeliveryChallansNewRoute
  InsightsLogisticsSummaryRoute: typeof InsightsLogisticsSummaryRoute
  MaterialMovementPendingRegisterRoute: typeof MaterialMovementPendingRegisterRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ReportsStockWithPartyRoute: typeof ReportsStockWithPartyRoute
  StockGroupsNewRoute: typeof StockGroupsNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DeliveryChallansIndexRoute: typeof DeliveryChallansIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StockGroupsIndexRoute: typeof StockGroupsIndexRoute
  StockRegisterIndexRoute: typeof StockRegisterIndexRoute
  CustomersEditIdRoute: typeof CustomersEditIdRoute
  DeliveryChallansCustomerCustomerNameRoute: typeof DeliveryChallansCustomerCustomerNameRoute
  DeliveryChallansEditIdRoute: typeof DeliveryChallansEditIdRoute
  DeliveryChallansPrintIdRoute: typeof DeliveryChallansPrintIdRoute
  ProductsEditIdRoute: typeof ProductsEditIdRoute
  StockGroupsEditIdRoute: typeof StockGroupsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-master': {
      id: '/transport-master'
      path: '/transport-master'
      fullPath: '/transport-master'
      preLoaderRoute: typeof TransportMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans/': {
      id: '/delivery-challans/'
      path: '/delivery-challans'
      fullPath: '/delivery-challans/'
      preLoaderRoute: typeof DeliveryChallansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans/new': {
      id: '/delivery-challans/new'
      path: '/delivery-challans/new'
      fullPath: '/delivery-challans/new'
      preLoaderRoute: typeof DeliveryChallansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/logistics-summary': {
      id: '/insights/logistics-summary'
      path: '/insights/logistics-summary'
      fullPath: '/insights/logistics-summary'
      preLoaderRoute: typeof InsightsLogisticsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-movement/pending-register': {
      id: '/material-movement/pending-register'
      path: '/material-movement/pending-register'
      fullPath: '/material-movement/pending-register'
      preLoaderRoute: typeof MaterialMovementPendingRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/stock-with-party': {
      id: '/reports/stock-with-party'
      path: '/reports/stock-with-party'
      fullPath: '/reports/stock-with-party'
      preLoaderRoute: typeof ReportsStockWithPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-groups/': {
      id: '/stock-groups/'
      path: '/stock-groups'
      fullPath: '/stock-groups/'
      preLoaderRoute: typeof StockGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-groups/new': {
      id: '/stock-groups/new'
      path: '/stock-groups/new'
      fullPath: '/stock-groups/new'
      preLoaderRoute: typeof StockGroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-register/': {
      id: '/stock-register/'
      path: '/stock-register'
      fullPath: '/stock-register/'
      preLoaderRoute: typeof StockRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-master/': {
      id: '/transport-master/'
      path: '/'
      fullPath: '/transport-master/'
      preLoaderRoute: typeof TransportMasterIndexRouteImport
      parentRoute: typeof TransportMasterRoute
    }
    '/transport-master/new': {
      id: '/transport-master/new'
      path: '/new'
      fullPath: '/transport-master/new'
      preLoaderRoute: typeof TransportMasterNewRouteImport
      parentRoute: typeof TransportMasterRoute
    }
    '/customers/edit/$id': {
      id: '/customers/edit/$id'
      path: '/customers/edit/$id'
      fullPath: '/customers/edit/$id'
      preLoaderRoute: typeof CustomersEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans/customer/$customerName': {
      id: '/delivery-challans/customer/$customerName'
      path: '/delivery-challans/customer/$customerName'
      fullPath: '/delivery-challans/customer/$customerName'
      preLoaderRoute: typeof DeliveryChallansCustomerCustomerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans/edit/$id': {
      id: '/delivery-challans/edit/$id'
      path: '/delivery-challans/edit/$id'
      fullPath: '/delivery-challans/edit/$id'
      preLoaderRoute: typeof DeliveryChallansEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans/print/$id': {
      id: '/delivery-challans/print/$id'
      path: '/delivery-challans/print/$id'
      fullPath: '/delivery-challans/print/$id'
      preLoaderRoute: typeof DeliveryChallansPrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/edit/$id': {
      id: '/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof ProductsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-groups/edit/$id': {
      id: '/stock-groups/edit/$id'
      path: '/stock-groups/edit/$id'
      fullPath: '/stock-groups/edit/$id'
      preLoaderRoute: typeof StockGroupsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-master/edit/$id': {
      id: '/transport-master/edit/$id'
      path: '/edit/$id'
      fullPath: '/transport-master/edit/$id'
      preLoaderRoute: typeof TransportMasterEditIdRouteImport
      parentRoute: typeof TransportMasterRoute
    }
  }
}

interface TransportMasterRouteChildren {
  TransportMasterNewRoute: typeof TransportMasterNewRoute
  TransportMasterIndexRoute: typeof TransportMasterIndexRoute
  TransportMasterEditIdRoute: typeof TransportMasterEditIdRoute
}

const TransportMasterRouteChildren: TransportMasterRouteChildren = {
  TransportMasterNewRoute: TransportMasterNewRoute,
  TransportMasterIndexRoute: TransportMasterIndexRoute,
  TransportMasterEditIdRoute: TransportMasterEditIdRoute,
}

const TransportMasterRouteWithChildren = TransportMasterRoute._addFileChildren(
  TransportMasterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TransportMasterRoute: TransportMasterRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
  DeliveryChallansNewRoute: DeliveryChallansNewRoute,
  InsightsLogisticsSummaryRoute: InsightsLogisticsSummaryRoute,
  MaterialMovementPendingRegisterRoute: MaterialMovementPendingRegisterRoute,
  ProductsNewRoute: ProductsNewRoute,
  ReportsStockWithPartyRoute: ReportsStockWithPartyRoute,
  StockGroupsNewRoute: StockGroupsNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DeliveryChallansIndexRoute: DeliveryChallansIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StockGroupsIndexRoute: StockGroupsIndexRoute,
  StockRegisterIndexRoute: StockRegisterIndexRoute,
  CustomersEditIdRoute: CustomersEditIdRoute,
  DeliveryChallansCustomerCustomerNameRoute:
    DeliveryChallansCustomerCustomerNameRoute,
  DeliveryChallansEditIdRoute: DeliveryChallansEditIdRoute,
  DeliveryChallansPrintIdRoute: DeliveryChallansPrintIdRoute,
  ProductsEditIdRoute: ProductsEditIdRoute,
  StockGroupsEditIdRoute: StockGroupsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
